### ISSUE TITLE
man directory task always changed on Ubuntu 20.04

### ISSUE THREAD

**Issue by andyshinn** [geerlingguy/ansible-role-java#130]
On Ubuntu 20.04 (and maybe others) the `man` directory task is changed when running next day (maybe automatic updates changing permissions?). Would be nice to be able to exclude this task (not sure what it is accomplishing).

**Comment by martinwe-adfinis** [comment]
This appears to be due to #110.

It looks like the intention behind that change was to simply be explicit about the mode for `/usr/share/man/man1` itself (i.e. good practice for `ansible.builtin.file`), but together with `recurse: true`, this now sets `0755` to all contained files as well.

Some digging shows that the `recurse: true` line appears to originally stem from 73a17ac2d174d7caff61040ffce8737087976160 (introduced to a test, later molecule (c393b08f14fbde447612c58471df7600e42164d7), later regular task (ee7c12b13aa594dc747892860e563f45794e94d0)).

Is it possible that this was an oversight, and could `recurse: true` be removed at this point?

**Comment by geerlingguy** [comment]
Can you file a PR with that change and we'll see if it passes the idempotence test?

**Comment by martinwe-adfinis** [comment]
Thanks for the fast response! I've opened #131.

**Comment by geerlingguy** [comment]
Looks like it worked. Merged! This is in the latest tag, too :)

**Comment by martinwe-adfinis** [comment]
Nice, thanks! :-D
