### ISSUE TITLE
Fails on new Debian machine

### ISSUE THREAD

**Issue by gpmayorga** [geerlingguy/ansible-role-java#35]
You need to add update_cache=yes to your Debian install otherwise it will fail in new operative systems (that have not yet run `apt-get update`) which is the case for any vagrant and AWS instances.

**Comment by gpmayorga** [comment]
TASK [geerlingguy.jenkins : Validate Jenkins is installed and register package name.] ***
fatal: [jenkins.dev.uts-squad.com]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'jenkins' is available"}

**Comment by gpmayorga** [comment]
`TASK [geerlingguy.java : Ensure Java is installed.] ****************************
failed: [jenkins.dev.uts-squad.com] (item=[u'openjdk-7-jdk']) => {"cache_update_time": 1481662267, "cache_updated": false, "failed": true, "item": ["openjdk-7-jdk"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'openjdk-7-jdk'' failed: E: Failed to fetch

**Comment by geerlingguy** [comment]
@gpmayorga - This is intentional: see https://github.com/geerlingguy/ansible-role-java/pull/33

The idea is that they playbook itself will update apt caches if needed (e.g. on provision or with some other condition). Otherwise every role would have to update apt caches on their own schedules which can affect idempotence and could lead to really slow builds...

See, for example, the test playbooks: https://github.com/geerlingguy/ansible-role-java/blob/master/tests/test.yml#L4-L8
