### ISSUE TITLE
Second time role run with different parameters - skipping

### ISSUE THREAD

**Issue by lioramilbaum** [geerlingguy/ansible-role-java#46]
I am launch an instance and installing java 7. Due to constrains of a following role, need to upgrade to java 8. Running the role again skipps everything and doesn't upgrade.

Here is the code snippet:

- name: Ensure java 8 is installed for Selenium plugin version 3.1.0 or up
  include_role:
    name: geerlingguy.java
  vars:
    java_packages: 'openjdk-8-jdk'
  when: 
  - "selenium.plugins[0].version | version_compare('3.1.0', '>=')"
  - "java_packages == 'openjdk-7-jdk'"

**Comment by geerlingguy** [comment]
@lioramilbaum - This role's installation task just verifies a particular java_packages set is installed (see https://github.com/geerlingguy/ansible-role-java/blob/master/tasks/setup-Debian.yml#L3) — for upgrading from Java 7 to Java 8, my preferences would be the following (in order of best solution to least likely to work easily):

  1. Build the server fresh, from a minimal base, so you can just install Java 8 and be done with it.
  2. In your playbook, have a `pre_task` or included task file that uninstalls Java 7. Then this role can install Java 8.
  3. Propose/send a PR for allowing this role to use different `state` parameters for the installation so the role could maybe be made to upgrade Java in place. This may or may not be easy to do (since Java is a bit different than other software in terms of configuration and package naming...).

**Comment by lioramilbaum** [comment]
I would consider options 1 and 2. 
Option 3 is unclear to me.

**Comment by geerlingguy** [comment]
In those cases, the best option is determined by what kind of infrastructure setup you have. If your servers are more or less disposable, I'd go with 1. If not, I'd go with 2 (or create a separate small playbook that just uninstalls Java in preparation for your playbook that then installs the right version of Java using this role).
